name: Build and Deploy PDF Data Site

on:
  schedule:
    - cron: '0 14 * * 3' # Every Wednesday at 8am Central Time (UTC-6)
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py to generate data
        run: python main.py --output-dir=dist/data

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.sigdex.io
          username: github@sigdex.io
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./pdfdata.sigdex.io/
          log-level: standard
